from google.cloud import bigquery

class StreamingSchema:
    schema = [
        bigquery.SchemaField("date", "DATE", "NULLABLE"),
        bigquery.SchemaField("event_timestamp", "INTEGER", "NULLABLE"),
        bigquery.SchemaField("event_name", "STRING", "NULLABLE"),
        bigquery.SchemaField(
            "event_params",
            "RECORD",
            "REPEATED",
            fields=(
                bigquery.SchemaField("key", "STRING", "NULLABLE"),
                bigquery.SchemaField(
                    "value",
                    "RECORD",
                    "NULLABLE",
                    fields=(
                        bigquery.SchemaField("string_value", "STRING", "NULLABLE"),
                        bigquery.SchemaField("int_value", "INTEGER", "NULLABLE"),
                        bigquery.SchemaField("float_value", "FLOAT", "NULLABLE"),
                    ),
                ),
            ),
        ),
        bigquery.SchemaField("user_id", "STRING", "NULLABLE"),
        bigquery.SchemaField("user_pseudo_id", "STRING", "NULLABLE"),
        bigquery.SchemaField(
            "privacy_info",
            "RECORD",
            "NULLABLE",
            fields=(
                bigquery.SchemaField("ad_storage", "BOOLEAN", "NULLABLE"),
                bigquery.SchemaField("ad_user_data", "BOOLEAN", "NULLABLE"),
                bigquery.SchemaField("ad_personalization", "BOOLEAN", "NULLABLE"),
                bigquery.SchemaField("analytics_storage", "BOOLEAN", "NULLABLE"),
                bigquery.SchemaField("functionality_storage", "BOOLEAN", "NULLABLE"),
                bigquery.SchemaField("personalization_storage", "BOOLEAN", "NULLABLE"),
                bigquery.SchemaField("security_storage", "BOOLEAN", "NULLABLE"),
            ),
        ),
        bigquery.SchemaField(
            "user_properties",
            "RECORD",
            "REPEATED",
            fields=(
                bigquery.SchemaField("key", "STRING", "NULLABLE"),
                bigquery.SchemaField(
                    "value",
                    "RECORD",
                    "NULLABLE",
                    fields=(
                        bigquery.SchemaField("string_value", "STRING", "NULLABLE"),
                        bigquery.SchemaField("int_value", "INTEGER", "NULLABLE"),
                        bigquery.SchemaField("float_value", "FLOAT", "NULLABLE"),
                        bigquery.SchemaField(
                            "set_timestamp_micros", "INTEGER", "NULLABLE"
                        ),
                    ),
                ),
            ),
        ),
        bigquery.SchemaField(
            "device",
            "RECORD",
            "NULLABLE",
            fields=(
                bigquery.SchemaField("category", "STRING", "NULLABLE"),
                bigquery.SchemaField("mobile_brand_name", "STRING", "NULLABLE"),
                bigquery.SchemaField("mobile_model_name", "STRING", "NULLABLE"),
                bigquery.SchemaField("mobile_marketing_name", "STRING", "NULLABLE"),
                bigquery.SchemaField("mobile_os_hardware_model", "STRING", "NULLABLE"),
                bigquery.SchemaField("operating_system", "STRING", "NULLABLE"),
                bigquery.SchemaField("operating_system_version", "STRING", "NULLABLE"),
                bigquery.SchemaField("vendor_id", "STRING", "NULLABLE"),
                bigquery.SchemaField("advertising_id", "STRING", "NULLABLE"),
                bigquery.SchemaField("language", "STRING", "NULLABLE"),
                bigquery.SchemaField("is_limited_ad_tracking", "STRING", "NULLABLE"),
                bigquery.SchemaField(
                    "web_info",
                    "RECORD",
                    "NULLABLE",
                    fields=(
                        bigquery.SchemaField("browser", "STRING", "NULLABLE"),
                        bigquery.SchemaField("browser_version", "STRING", "NULLABLE"),
                    ),
                ),
                bigquery.SchemaField("is_bot", "BOOLEAN", "NULLABLE"),
                bigquery.SchemaField("user_agent", "STRING", "NULLABLE"),
            ),
        ),
        bigquery.SchemaField(
            "geo",
            "RECORD",
            "NULLABLE",
            fields=(
                bigquery.SchemaField("country", "STRING", "NULLABLE"),
                bigquery.SchemaField("region", "STRING", "NULLABLE"),
                bigquery.SchemaField("city", "STRING", "NULLABLE"),
            ),
        ),
        bigquery.SchemaField(
            "app_info",
            "RECORD",
            "NULLABLE",
            fields=(
                bigquery.SchemaField("id", "STRING", "NULLABLE"),
                bigquery.SchemaField("version", "STRING", "NULLABLE"),
                bigquery.SchemaField("install_store", "STRING", "NULLABLE"),
                bigquery.SchemaField("firebase_app_id", "STRING", "NULLABLE"),
                bigquery.SchemaField("install_source", "STRING", "NULLABLE"),
            ),
        ),
        # collected_traffic_source - raw UTM and referrer data (not session-attributed)
        bigquery.SchemaField(
            "collected_traffic_source",
            "RECORD",
            "NULLABLE",
            fields=(
                bigquery.SchemaField("manual_campaign_id", "STRING", "NULLABLE"),
                bigquery.SchemaField("manual_campaign_name", "STRING", "NULLABLE"),
                bigquery.SchemaField("manual_source", "STRING", "NULLABLE"),
                bigquery.SchemaField("manual_medium", "STRING", "NULLABLE"),
                bigquery.SchemaField("manual_term", "STRING", "NULLABLE"),
                bigquery.SchemaField("manual_content", "STRING", "NULLABLE"),
                bigquery.SchemaField("manual_source_platform", "STRING", "NULLABLE"),
                bigquery.SchemaField("manual_creative_format", "STRING", "NULLABLE"),
                bigquery.SchemaField("manual_marketing_tactic", "STRING", "NULLABLE"),
                bigquery.SchemaField("gclid", "STRING", "NULLABLE"),
                bigquery.SchemaField("dclid", "STRING", "NULLABLE"),
                bigquery.SchemaField("srsltid", "STRING", "NULLABLE"),
                bigquery.SchemaField("fbclid", "STRING", "NULLABLE"),
            ),
        ),
        bigquery.SchemaField("stream_id", "INTEGER", "NULLABLE"),
        bigquery.SchemaField(
            "ecommerce",
            "RECORD",
            "NULLABLE",
            fields=(
                bigquery.SchemaField("transaction_id", "STRING", "NULLABLE"),
                bigquery.SchemaField("value", "FLOAT", "NULLABLE"),
                bigquery.SchemaField("currency", "STRING", "NULLABLE"),
                bigquery.SchemaField("coupon", "STRING", "NULLABLE"),
                bigquery.SchemaField("payment_type", "STRING", "NULLABLE"),
                bigquery.SchemaField("shipping_tier", "STRING", "NULLABLE"),
                bigquery.SchemaField("item_list_id", "STRING", "NULLABLE"),
                bigquery.SchemaField("item_list_name", "STRING", "NULLABLE"),
                bigquery.SchemaField("promotion_id", "STRING", "NULLABLE"),
                bigquery.SchemaField("promotion_name", "STRING", "NULLABLE"),
                bigquery.SchemaField("creative_name", "STRING", "NULLABLE"),
                bigquery.SchemaField("creative_slot", "STRING", "NULLABLE"),
                bigquery.SchemaField("total_item_quantity", "INTEGER", "NULLABLE"),
            ),
        ),
        bigquery.SchemaField(
            "items",
            "RECORD",
            "REPEATED",
            fields=(
                bigquery.SchemaField("item_id", "STRING", "NULLABLE"),
                bigquery.SchemaField("item_name", "STRING", "NULLABLE"),
                bigquery.SchemaField("affiliation", "STRING", "NULLABLE"),
                bigquery.SchemaField("coupon", "STRING", "NULLABLE"),
                bigquery.SchemaField("discount", "FLOAT", "NULLABLE"),
                bigquery.SchemaField("index", "INTEGER", "NULLABLE"),
                bigquery.SchemaField("item_brand", "STRING", "NULLABLE"),
                bigquery.SchemaField("item_category", "STRING", "NULLABLE"),
                bigquery.SchemaField("item_category2", "STRING", "NULLABLE"),
                bigquery.SchemaField("item_category3", "STRING", "NULLABLE"),
                bigquery.SchemaField("item_category4", "STRING", "NULLABLE"),
                bigquery.SchemaField("item_category5", "STRING", "NULLABLE"),
                bigquery.SchemaField("item_list_id", "STRING", "NULLABLE"),
                bigquery.SchemaField("item_list_name", "STRING", "NULLABLE"),
                bigquery.SchemaField("item_variant", "STRING", "NULLABLE"),
                bigquery.SchemaField("location_id", "STRING", "NULLABLE"),
                bigquery.SchemaField("price", "FLOAT", "NULLABLE"),
                bigquery.SchemaField("promotion_id", "STRING", "NULLABLE"),
                bigquery.SchemaField("promotion_name", "STRING", "NULLABLE"),
                bigquery.SchemaField("creative_name", "STRING", "NULLABLE"),
                bigquery.SchemaField("creative_slot", "STRING", "NULLABLE"),
                bigquery.SchemaField("quantity", "INTEGER", "NULLABLE"),
            ),
        ),
        bigquery.SchemaField("ip", "STRING", "NULLABLE"),
        bigquery.SchemaField("synced_at_utc_", "TIMESTAMP", "NULLABLE"),
        bigquery.SchemaField("synced_at_micros_", "INTEGER", "NULLABLE"),
        bigquery.SchemaField("subscription_name", "STRING", "NULLABLE"),
        bigquery.SchemaField("message_id", "STRING", "NULLABLE"),
        bigquery.SchemaField("publish_time", "TIMESTAMP", "NULLABLE"),
        bigquery.SchemaField("attributes", "JSON", "NULLABLE"),
    ]

    partitioning_field = "date"
    clustering_field = ["user_pseudo_id", "event_name"]

streaming_schema = StreamingSchema()
